/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checkers;

/**
 *
 * @author hyunchoi98
 */
public class CheckersGUI extends javax.swing.JFrame {

    /**
     * Creates new form CheckersGUI
     */
    public CheckersGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 40, 50, 43);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 100, 94, 43);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 100, 94, 43);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 40, 94, 43);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 40, 94, 43);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 40, 94, 43);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(500, 100, 94, 43);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 160, 94, 43);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(180, 170, 94, 43);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(250, 100, 94, 43);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(440, 170, 94, 43);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/white.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(310, 170, 94, 43);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/board.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 30, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckersGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckersGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
